name: Super-Linter

on: push

jobs:
  test:
    name: Test actions behaviour
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        run: pwd
