name: test

on: push

jobs:
  test:
    name: Test actions behaviour
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check root directory
        run: pwd
